"""
report.py — PDF Report Generator for the Vulnerability Scanner.

Generates a professional, colour-coded PDF report using ReportLab Platypus.
"""

import os
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)
from reportlab.platypus.flowables import HRFlowable

from scanner import ScanResult, Finding, CRITICAL, HIGH, MEDIUM, LOW, INFO, SEVERITY_ORDER

# ── Colour palette ────────────────────────────────────────────────────────────
COL_CRITICAL = colors.HexColor("#C0392B")
COL_HIGH     = colors.HexColor("#E67E22")
COL_MEDIUM   = colors.HexColor("#F1C40F")
COL_LOW      = colors.HexColor("#27AE60")
COL_INFO     = colors.HexColor("#2980B9")
COL_BG       = colors.HexColor("#1A1A2E")   # dark header bg
COL_ACCENT   = colors.HexColor("#E94560")   # accent red
COL_LIGHT    = colors.HexColor("#F5F5F5")
COL_MID      = colors.HexColor("#ECECEC")
COL_WHITE    = colors.white
COL_TEXT     = colors.HexColor("#222222")

SEV_COLOR = {
    CRITICAL: COL_CRITICAL,
    HIGH:     COL_HIGH,
    MEDIUM:   COL_MEDIUM,
    LOW:      COL_LOW,
    INFO:     COL_INFO,
}

SEV_BG = {
    CRITICAL: colors.HexColor("#FDECEA"),
    HIGH:     colors.HexColor("#FEF0E6"),
    MEDIUM:   colors.HexColor("#FEFAE6"),
    LOW:      colors.HexColor("#E9F7EF"),
    INFO:     colors.HexColor("#EBF5FB"),
}


# ── Style helpers ─────────────────────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()

    def add(name, parent="Normal", **kw):
        base.add(ParagraphStyle(name=name, parent=base[parent], **kw))

    add("ReportTitle",  "Title",
        fontSize=26, textColor=COL_WHITE, alignment=TA_CENTER,
        spaceAfter=4, fontName="Helvetica-Bold")

    add("ReportSubtitle", "Normal",
        fontSize=11, textColor=colors.HexColor("#CCCCCC"),
        alignment=TA_CENTER, spaceAfter=2)

    add("SectionHeader", "Normal",
        fontSize=13, textColor=COL_BG, fontName="Helvetica-Bold",
        spaceBefore=10, spaceAfter=4,
        borderPad=4)

    add("FindingTitle", "Normal",
        fontSize=10, textColor=COL_TEXT, fontName="Helvetica-Bold",
        spaceBefore=2, spaceAfter=1)

    add("FindingBody", "Normal",
        fontSize=9, textColor=COL_TEXT,
        leading=13, spaceAfter=2)

    add("FindingRec", "Normal",
        fontSize=9, textColor=colors.HexColor("#1A5276"),
        fontName="Helvetica-Oblique", leading=13, spaceAfter=2)

    add("MonoSmall", "Normal",
        fontName="Courier", fontSize=7.5,
        textColor=colors.HexColor("#555555"),
        backColor=colors.HexColor("#F4F4F4"),
        leading=11)

    add("TableHeader", "Normal",
        fontSize=9, textColor=COL_WHITE, fontName="Helvetica-Bold",
        alignment=TA_CENTER)

    add("TableCell", "Normal",
        fontSize=9, textColor=COL_TEXT, alignment=TA_CENTER)

    add("Footer", "Normal",
        fontSize=7.5, textColor=colors.HexColor("#888888"), alignment=TA_CENTER)

    return base


# ── Page template (header/footer) ─────────────────────────────────────────────
class _PageDecoration:
    def __init__(self, title: str):
        self.title = title

    def __call__(self, canvas, doc):
        canvas.saveState()
        w, h = A4

        # ── top bar ──
        canvas.setFillColor(COL_BG)
        canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
        canvas.setFillColor(COL_ACCENT)
        canvas.rect(0, h - 19.5*mm, w, 1.5*mm, fill=1, stroke=0)

        canvas.setFont("Helvetica-Bold", 9)
        canvas.setFillColor(COL_WHITE)
        canvas.drawString(15*mm, h - 12*mm, self.title)
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#AAAAAA"))
        canvas.drawRightString(w - 15*mm, h - 12*mm,
                               f"CONFIDENTIAL  |  Page {doc.page}")

        # ── bottom bar ──
        canvas.setFillColor(COL_BG)
        canvas.rect(0, 0, w, 10*mm, fill=1, stroke=0)
        canvas.setFillColor(COL_ACCENT)
        canvas.rect(0, 10*mm, w, 0.8*mm, fill=1, stroke=0)
        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#AAAAAA"))
        canvas.drawCentredString(w / 2, 3.5*mm,
            "Generated by Linux Vulnerability Report Generator  •  For internal use only")

        canvas.restoreState()


# ── Building blocks ───────────────────────────────────────────────────────────
def _cover_block(result: ScanResult, styles) -> list:
    w, h = A4
    story = []

    # Dark hero banner (drawn as a coloured table)
    banner_data = [[
        Paragraph(
            "<font color='#E94560'>&#9632;</font> Linux Vulnerability Report",
            styles["ReportTitle"]
        )
    ]]
    banner_tbl = Table(banner_data, colWidths=[w - 30*mm])
    banner_tbl.setStyle(TableStyle([
        ("BACKGROUND",  (0,0), (-1,-1), COL_BG),
        ("TOPPADDING",  (0,0), (-1,-1), 20),
        ("BOTTOMPADDING",(0,0),(-1,-1), 14),
        ("LEFTPADDING", (0,0), (-1,-1), 10),
        ("RIGHTPADDING",(0,0), (-1,-1), 10),
    ]))
    story.append(banner_tbl)
    story.append(Spacer(1, 6*mm))

    # Meta table
    meta = [
        ["Target Host",  result.hostname],
        ["OS / Platform",result.os_info],
        ["Scan Date",    result.scan_time],
        ["Total Findings", str(len(result.findings))],
        ["Report Classification", "CONFIDENTIAL"],
    ]
    mt = Table(meta, colWidths=[55*mm, w - 30*mm - 55*mm])
    mt.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (0,-1), COL_BG),
        ("TEXTCOLOR",    (0,0), (0,-1), COL_WHITE),
        ("FONTNAME",     (0,0), (0,-1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,0), (-1,-1), 9),
        ("BACKGROUND",   (1,0), (1,-1), COL_LIGHT),
        ("ROWBACKGROUNDS",(1,0),(1,-1), [COL_LIGHT, COL_MID]),
        ("GRID",         (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
    ]))
    story.append(mt)
    story.append(Spacer(1, 8*mm))
    return story


def _summary_table(result: ScanResult, styles) -> list:
    story = []
    story.append(Paragraph("Executive Summary", styles["SectionHeader"]))
    story.append(HRFlowable(width="100%", thickness=1.5,
                            color=COL_ACCENT, spaceAfter=6))

    counts = result.summary()
    headers = [Paragraph(s, styles["TableHeader"]) for s in
               ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "TOTAL"]]
    values  = [
        Paragraph(str(counts[CRITICAL]), styles["TableCell"]),
        Paragraph(str(counts[HIGH]),     styles["TableCell"]),
        Paragraph(str(counts[MEDIUM]),   styles["TableCell"]),
        Paragraph(str(counts[LOW]),      styles["TableCell"]),
        Paragraph(str(counts[INFO]),     styles["TableCell"]),
        Paragraph(str(len(result.findings)), styles["TableCell"]),
    ]

    w, _ = A4
    col_w = (w - 30*mm) / 6
    tbl = Table([headers, values], colWidths=[col_w]*6)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (0,0), COL_CRITICAL),
        ("BACKGROUND",   (1,0), (1,0), COL_HIGH),
        ("BACKGROUND",   (2,0), (2,0), COL_MEDIUM),
        ("BACKGROUND",   (3,0), (3,0), COL_LOW),
        ("BACKGROUND",   (4,0), (4,0), COL_INFO),
        ("BACKGROUND",   (5,0), (5,0), COL_BG),
        ("BACKGROUND",   (0,1), (-1,1), COL_LIGHT),
        ("FONTNAME",     (0,1), (-1,1), "Helvetica-Bold"),
        ("FONTSIZE",     (0,1), (-1,1), 14),
        ("ALIGN",        (0,0), (-1,-1), "CENTER"),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 7),
        ("BOTTOMPADDING",(0,0), (-1,-1), 7),
        ("GRID",         (0,0), (-1,-1), 0.5, colors.HexColor("#CCCCCC")),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 5*mm))

    # Risk rating
    crit = counts[CRITICAL]
    hi   = counts[HIGH]
    if crit > 0:
        risk, risk_color = "CRITICAL RISK", COL_CRITICAL
        summary_txt = (
            f"The system has <b>{crit} CRITICAL</b> finding(s) requiring <b>immediate remediation</b>. "
            f"Additionally, {hi} HIGH severity issue(s) were found."
        )
    elif hi > 0:
        risk, risk_color = "HIGH RISK", COL_HIGH
        summary_txt = (
            f"No critical issues found, but <b>{hi} HIGH</b> severity finding(s) require prompt attention."
        )
    elif counts[MEDIUM] > 0:
        risk, risk_color = "MEDIUM RISK", COL_MEDIUM
        summary_txt = "No critical or high issues found. Medium severity findings should be scheduled for remediation."
    else:
        risk, risk_color = "LOW RISK", COL_LOW
        summary_txt = "System appears relatively secure. Continue monitoring and applying updates."

    risk_data = [[
        Paragraph(f"Overall Risk Rating: <b>{risk}</b>",
                  ParagraphStyle("RiskLabel", parent=styles["Normal"],
                                 textColor=COL_WHITE, fontSize=11,
                                 fontName="Helvetica-Bold")),
    ]]
    risk_tbl = Table(risk_data, colWidths=[A4[0] - 30*mm])
    risk_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), risk_color),
        ("TOPPADDING",   (0,0), (-1,-1), 8),
        ("BOTTOMPADDING",(0,0), (-1,-1), 8),
        ("LEFTPADDING",  (0,0), (-1,-1), 10),
    ]))
    story.append(risk_tbl)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(summary_txt, styles["FindingBody"]))
    story.append(Spacer(1, 6*mm))
    return story


def _finding_block(f: Finding, styles) -> list:
    col  = SEV_COLOR[f.severity]
    bg   = SEV_BG[f.severity]
    w, _ = A4

    # Severity badge + title in one row
    badge_para = Paragraph(
        f"<font color='white'><b> {f.severity} </b></font>",
        ParagraphStyle("Badge", parent=styles["Normal"],
                       fontSize=8, backColor=col,
                       textColor=COL_WHITE, fontName="Helvetica-Bold",
                       borderPad=2)
    )
    title_para = Paragraph(f.title, styles["FindingTitle"])

    header_tbl = Table(
        [[badge_para, title_para]],
        colWidths=[22*mm, w - 30*mm - 22*mm],
    )
    header_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), bg),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 5),
        ("BOTTOMPADDING",(0,0), (-1,-1), 5),
        ("LEFTPADDING",  (0,0), (0,0),   6),
        ("LEFTPADDING",  (1,0), (1,0),   8),
        ("LINEBELOW",    (0,0), (-1,-1), 1.5, col),
    ]))

    body_rows = [
        [Paragraph("<b>Check:</b>",          styles["FindingBody"]),
         Paragraph(f.check,                  styles["FindingBody"])],
        [Paragraph("<b>Description:</b>",    styles["FindingBody"]),
         Paragraph(f.description,            styles["FindingBody"])],
        [Paragraph("<b>Recommendation:</b>", styles["FindingBody"]),
         Paragraph(f"<i>{f.recommendation}</i>", styles["FindingRec"])],
    ]

    if f.raw_output:
        raw_text = f.raw_output.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        body_rows.append([
            Paragraph("<b>Evidence:</b>", styles["FindingBody"]),
            Paragraph(raw_text,          styles["MonoSmall"]),
        ])

    body_tbl = Table(body_rows, colWidths=[30*mm, w - 30*mm - 30*mm])
    body_tbl.setStyle(TableStyle([
        ("BACKGROUND",   (0,0), (-1,-1), bg),
        ("VALIGN",       (0,0), (-1,-1), "TOP"),
        ("TOPPADDING",   (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("LINEBELOW",    (0,-1),(-1,-1), 0.3, colors.HexColor("#CCCCCC")),
    ]))

    return [KeepTogether([header_tbl, body_tbl, Spacer(1, 3*mm)])]


def _checklist_table(result: ScanResult, styles) -> list:
    """One-page remediation checklist."""
    story = [PageBreak()]
    story.append(Paragraph("Remediation Checklist", styles["SectionHeader"]))
    story.append(HRFlowable(width="100%", thickness=1.5,
                            color=COL_ACCENT, spaceAfter=6))

    w, _ = A4
    rows = [[
        Paragraph("Severity",       styles["TableHeader"]),
        Paragraph("Finding",        styles["TableHeader"]),
        Paragraph("Check",          styles["TableHeader"]),
        Paragraph("Status",         styles["TableHeader"]),
    ]]

    row_colors = []
    for i, f in enumerate(result.sorted_findings(), 1):
        if f.severity == INFO:
            continue
        rows.append([
            Paragraph(f.severity, ParagraphStyle(
                "SevCell", parent=styles["TableCell"],
                textColor=SEV_COLOR[f.severity], fontName="Helvetica-Bold")),
            Paragraph(f.title[:80] + ("…" if len(f.title) > 80 else ""),
                      styles["TableCell"]),
            Paragraph(f.check, styles["TableCell"]),
            Paragraph("[ ]", styles["TableCell"]),
        ])
        row_colors.append(SEV_BG[f.severity])

    col_w = [22*mm, (w-30*mm)*0.52, 35*mm, 18*mm]
    tbl = Table(rows, colWidths=col_w, repeatRows=1)

    style_cmds = [
        ("BACKGROUND",   (0,0), (-1,0), COL_BG),
        ("GRID",         (0,0), (-1,-1), 0.4, colors.HexColor("#CCCCCC")),
        ("VALIGN",       (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING",   (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ("LEFTPADDING",  (0,0), (-1,-1), 5),
    ]
    for ri, bg in enumerate(row_colors, 1):
        style_cmds.append(("BACKGROUND", (0,ri), (-1,ri), bg))

    tbl.setStyle(TableStyle(style_cmds))
    story.append(tbl)
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph(
        "<i>Tick each box as findings are remediated. Re-run the scanner to verify fixes.</i>",
        styles["Footer"]
    ))
    return story


# ── Main entry point ──────────────────────────────────────────────────────────
def generate_pdf(result: ScanResult, output_path: str = "vulnerability_report.pdf") -> str:
    styles = _styles()
    doc_title = f"Vulnerability Report — {result.hostname}"

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=22*mm, bottomMargin=14*mm,
        title=doc_title,
        author="Linux Vulnerability Report Generator",
        subject="Security Audit",
    )

    decoration = _PageDecoration(doc_title)
    story = []

    # Cover + summary
    story += _cover_block(result, styles)
    story += _summary_table(result, styles)

    # Findings by severity
    story.append(Paragraph("Detailed Findings", styles["SectionHeader"]))
    story.append(HRFlowable(width="100%", thickness=1.5,
                            color=COL_ACCENT, spaceAfter=6))

    current_sev = None
    for f in result.sorted_findings():
        if f.severity != current_sev:
            current_sev = f.severity
            col = SEV_COLOR[f.severity]
            label_data = [[Paragraph(
                f"<font color='white'><b>{f.severity} FINDINGS</b></font>",
                styles["TableHeader"]
            )]]
            label_tbl = Table(label_data, colWidths=[A4[0] - 30*mm])
            label_tbl.setStyle(TableStyle([
                ("BACKGROUND",   (0,0), (-1,-1), col),
                ("TOPPADDING",   (0,0), (-1,-1), 5),
                ("BOTTOMPADDING",(0,0), (-1,-1), 5),
            ]))
            story.append(Spacer(1, 4*mm))
            story.append(label_tbl)
            story.append(Spacer(1, 2*mm))

        story += _finding_block(f, styles)

    # Checklist page
    story += _checklist_table(result, styles)

    doc.build(story, onFirstPage=decoration, onLaterPages=decoration)
    return output_path
